.\" $OpenBSD$
.\"
.\" Copyright (c) 2023 Alexander Bluhm <bluhm@genua.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SPLICEBENCH 1
.Os
.Sh NAME
.Nm splicebench
.Nd socket splicing network benchmarking tool
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl 46cu
.Op Fl b Ar bufsize
.Op Fl i Ar idle
.Op Fl N Ar repeat
.Op Fl n Ar multi
.Op Fl t Ar timeout
.Op Ar listen
.Op Ar bindout
.Ar connect
.Ek
.Sh DESCRIPTION
The
.Nm
utility implements a relay for OpenBSD socket splicing.
It accepts a TCP connection from a client, connects to a server and
splices traffic unidirectionally.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 4
Force
.Nm
to use IPv4 listen address only.
.It Fl 6
Force
.Nm
to use IPv6 listen addresses only.
.It Fl b Ar bufsize
Set size of send and receive socket buffer.
.It Fl c
Copy mode can be selected to compare performance to splice.
.It Fl i Ar idle
After a period of not receiving any UDP packets, splice will stop.
Default is 1 second, 0 will ignore idle periods.
.It Fl N Ar repeat
Create multiple listen sockets on consecutive IP addresses.
Each incoming request will be spliced to a different consecutive
connect address.
.It Fl n Ar multi
Accept multiple TCP connections at listen socket.
Run until all splicings have finished.
.It Fl t Ar timeout
Waiting for connection and splicing are stopped after timeout.
When splicing, all data has to be transfered within this timeout
plus two seconds.
Disable timeout with 0 and run forever.
Default is 1 second.
.It Fl u
Use UDP sockets instead of TCP.
.El
.Pp
Parameters
.Ar listen ,
.Ar bindout
and
.Ar connect
are used to to specify IP addresses and port numbers.
If the port it omitted for
.Ar listen
or
.Ar connect ,
12345 is used.
Port 0 for
.Ar listen
or
.Ar bindout
lets the kernel choose one.
The unspecified address can be use to set the port or address family
only.
.\" .Sh EXAMPLES
.Sh DIAGNOSTICS
.Bl -diag
.It "splice: payload 573635832, begin 1706272738.460010, end 1706272752.032744, duration 13.572734, bit/s 3.38111e+08, start 1706272738.022382, stop 1706272752.032814"
.Pp
Summary of
.Nm
splice or copy action.
Status is printed as single line just before exit.
.Bl -tag -width 8
.It payload
Bytes in the TCP stream or UDP payload of all packets.
.It begin
Time stamp just before the splicing starts.
.It end
Time stamp after the splicing stopped.
If
.Fl i Ar idle
is set, end is the time of the final packet before idle timed out.
.It start
Time stamp after listen socket is bound.
.It stop
Time stamp before sockets are closed.
.El
.El
.Sh SEE ALSO
.Xr setsockopt 2 ,
.Xr sosplice 9
.Sh AUTHORS
The
.Nm
program was written by
.An Alexander Bluhm Aq Mt bluhm@genua.de .
