.\" $OpenBSD$
.\"
.\" Copyright (c) 2023 Alexander Bluhm <bluhm@genua.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SPLICEBENCH 1
.Os
.Sh NAME
.Nm splicebench
.Nd socket splicing network benchmarking tool
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl 46cu
.Op Fl t Ar timeout
.Op Ar listen
.Op Ar bindout
.Ar connect
.Ek
.Sh DESCRIPTION
The
.Nm
utility implements a relay for OpenBSD socket splicing.
It accepts a TCP connection from a client, connects to a server and
splices traffic unidirectionally.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 4
Force
.Nm
to use IPv4 listen address only.
.It Fl 6
Force
.Nm
to use IPv6 listen addresses only.
.It Fl c
Copy mode can be selected to compare performance to splice.
.It Fl t Ar timeout
When splicing UDP, close the connection after idle timeout.
Default is 1 second.
.It Fl u
Use UDP sockets instead of TCP.
.El
.Pp
Parameters
.Ar listen ,
.Ar bindout
and
.Ar connect
are used to to specify IP addresses and port numbers.
If the port it omitted for
.Ar listen
or
.Ar connect ,
12345 is used.
Port 0 for
.Ar listen
or
.Ar bindout
lets the kernel choose one.
The unspecified address can be use to set the port or address family
only.
.\" .Sh EXAMPLES
.Sh SEE ALSO
.Xr setsockopt 2 ,
.Xr sosplice 9
.Sh AUTHORS
The
.Nm
program was written by
.An Alexander Bluhm Aq Mt bluhm@genua.de .
